### ISSUE TITLE
Support for calibration (on osx)?

### ISSUE THREAD

**Issue by tyhenry** [TatsuyaOGth/ofxEyeTribe#2]
Thank you for the addon.  I have it working with my mac - but is calibration only supported through the windows UI?  Or is there a way to calibrate using the addon itself?  Thanks!

**Comment by TatsuyaOGth** [comment]
Hi tyhenry, you can calibration on osx by my addon (ver. 0.4). If it doesn't work on your mac, could you tell me the appeared messages on your console? Or could you show me the screen capture? Thank you!

**Comment by tyhenry** [comment]
My apologies!  I was using an older version.  v0.4 works like a charm.  Thank you for the addon!  It's a huge help.
